baseURL = 'https://blog.morielclouds.com/'
languageCode = 'en-us'
title = "Morile's Mauni Blog"
theme = 'hugo-blog-awesome'

# ~~~~~~~~~~~~~~~~~~ Top ~~~~~~~~~~~~~~~~~~~~~ 
[menu]
[[menu.main]]
name = 'Home'
url = '/'
weight = 1

[[menu.main]]
name = 'Posts'
url = '/posts'
weight = 2

# ~~~~~~~~~~~~~~~~ Middle ~~~~~~~~~~~~~~~~~~~~
[params]
description = 'Head of the tech table'
mainSections = ['posts']
sitename = "Moriel's Mauni blog"
defaultColor = 'dark'

[params.author]
avatar = 'img/profile.jpeg'
intro = 'Moriel Mauni'
description = 'DevOps'

[[params.socialIcons]]
name = 'github'
url = 'https://github.com/MorielMauni'

[[params.socialIcons]]
name = 'linkedin'
url = 'https://www.linkedin.com/in/morielmauni/'

[[params.socialIcons]]
name = 'email'
url = 'morielmauni@gmail.com'
